### ISSUE TITLE
TODO: 

### ISSUE THREAD

**Issue by Yousef-Fares** [Yousef-Fares/Assignment_1_COSC1078_Yousef#1]
TODO:

Unfinished pages:
- [x]  Interest in IT
- [x]  Ideal Job
- [x]  Profile
- [x]  Project Idea
- [x]  References

Other:
- [x]  Write up references
- [x]  Add padding to face img on InterestInIT page

**Comment by Yousef-Fares** [comment]
TODO 2:

- [x] Harvard style referencing
- [x] reference list complete
- [x] background sorted
- [x] Push, finalize, check remote, github pages URL (refer to W3 tut notes)

Word Doc: 

- [x] Put all content into word Doc and section it
- [x] Add Github Repo URL + GitHub Pages to Top
- [x] Convert to PDF
- [x] Upload PDF to Assignment 1
